"use strict";
/* detail.js — Cafe detail page.
   Loaded by index.html; script order matters (config first, boot last). */
/* ---------- detail ---------- */
function photoLabel(c){ if(c&&c.photo)return "📷 My drink"; const u=gphotoFor(c); if(u)return "📷 Google Maps"; return ""; }
function setHeroTag(c){ const t=$("d-tagphoto"); if(!t)return; const l=photoLabel(c); if(l){ t.textContent=l; t.style.display=""; } else { t.style.display="none"; } }
function fmtPrice(p){ p=(p==null?"":String(p)).trim(); if(!p)return ""; const m=p.replace(/[^0-9.]/g,""); if(m&&!isNaN(parseFloat(m)))return "$"+parseFloat(m).toFixed(2); return p; }
function reorderVal(d){ if(!d)return ""; const v=d.reorder; if(v==="yes"||v===true)return "yes"; if(v==="no"||v===false)return "no"; if(v==="neutral")return "neutral"; return ""; }
function reorderTally(c){ let yes=0,no=0,neutral=0; ((c&&c.drinks)||[]).forEach(d=>{ const v=reorderVal(d); if(v==="yes")yes++; else if(v==="no")no++; else if(v==="neutral")neutral++; }); return {yes:yes,no:no,neutral:neutral,total:yes+no+neutral}; }
function renderReorderRollup(c){ const re=$("d-reorder"); if(!re)return; const t=reorderTally(c); if(!t.total){ re.style.display="none"; re.innerHTML=""; return; } re.style.display="flex"; const pct=Math.round(t.yes/t.total*100); re.innerHTML='<span class="ro-badge '+(t.yes>=t.no?"yes":"no")+'">👍 Liked '+t.yes+' of '+t.total+'</span><span class="ro-bar"><i style="width:'+pct+'%"></i></span>'; }
/* Compact form for the detail line — the rail already carries the colour, so the chip
   only needs the glyph. The full-text badge is still used elsewhere. */
function reorderChip(d){ const v=reorderVal(d); if(!v)return ""; const e=v==="yes"?"👍":(v==="no"?"👎":"😐"); return '<span class="reorder '+v+'">'+e+'</span> '; }
function setReorder(btn,v){ const wrap=btn.parentNode; const hid=wrap.querySelector(".dre"); hid.value=(hid.value===v)?"": v; wrap.querySelectorAll(".rbtn").forEach(b=>b.classList.remove("on")); if(hid.value)wrap.querySelector(".rbtn."+hid.value).classList.add("on"); }
function openDetail(id,from){ const c=cafes.find(x=>x.id===id); if(!c)return; if(from)lastMain=from; curId=id; const hero=$("d-hero"); if($("d-hero-emoji"))$("d-hero-emoji").textContent=(c.emoji||"☕"); const gp0=(_imgFail[c.id]?null:gphotoFor(c)); if(gp0){ hero.className="hero"; hero.style.background=""; hero.style.backgroundImage='url("'+safeUrl(gp0)+'")'; const _hp=new Image(); _hp.onerror=function(){ _imgFail[c.id]=1; if(c.gphoto)delete c.gphoto; if(gphotoCache[c.id]!==undefined){ delete gphotoCache[c.id]; saveGphotoCache(); } if(curId===c.id){ const h=$("d-hero"); h.className="hero nophoto"; h.style.background=nophotoBg(c.name); } }; _hp.src=safeUrl(gp0); } else { hero.className="hero nophoto"; hero.style.background=nophotoBg(c.name); } setHeroTag(c); if(!c.photo){ fetchPlacePhoto(c,(url)=>{ if(url && curId===c.id){ const h=$("d-hero"); h.className="hero"; h.style.background=""; h.style.backgroundImage='url("'+safeUrl(url)+'")'; } if(curId===c.id)setHeroTag(c); applyCardPhoto(c.id,url); }); } $("d-name").textContent=c.name; $("d-stars").innerHTML=(c.rating?'<b>'+"★".repeat(c.rating)+"</b>":"")+"★".repeat(5-(c.rating||0)); $("d-meta").innerHTML=[c.area?esc(c.area):"",c.matches?('<span class="scorebadge">⚖️ '+eloScore(c)+' · '+c.matches+(c.matches===1?" compare":" compares")+'</span>'):"",(isAdmin&&c.updated)?("edited "+esc(fmtEdited(c.updated))):""].filter(Boolean).join("  ·  "); try{ renderChaser(c); }catch(e){ console.warn("renderChaser failed",e); } $("d-fav").textContent=c.fav?"❤️":"🤍"; if($("d-wish")){ $("d-wish").textContent="🔖"; $("d-wish").style.opacity=c.wish?"1":".45"; } renderReorderRollup(c); $("d-tags").innerHTML=(c.tags||[]).map(t=>'<span class="chip">'+esc(t)+'</span>').join(""); const _bk=(c.brand||"").trim().toLowerCase()||(c.name||"").trim().toLowerCase(); const _sibs=cafes.filter(x=>(((x.brand||"").trim().toLowerCase())||((x.name||"").trim().toLowerCase()))===_bk).sort((a,b)=>(a.area||"").localeCompare(b.area||"")); const _le=$("d-locs"); if(_sibs.length>1){ _le.style.display="flex"; _le.innerHTML=_sibs.map(x=>'<span class="locpill'+(x.id===c.id?' on':'')+'" onclick="openDetail(\''+x.id+'\',\''+(lastMain||"list")+'\')">📍 '+esc(x.area||x.name||"Location")+'</span>').join(""); } else { _le.style.display="none"; _le.innerHTML=""; } const _lastDate=d=>((d.dates||[]).filter(Boolean).sort().slice(-1)[0])||""; const _dsorted=(c.drinks||[]).slice().sort((a,b)=>_lastDate(b).localeCompare(_lastDate(a))); /* Two lines, not four: verdict + options + latest date share line 2, and the extra-dates
   line only appears for the handful of drinks with more than one visit date. */
$("d-drinks").innerHTML=_dsorted.length?_dsorted.map(d=>{ const ds=(d.dates||[]).filter(Boolean).slice().sort(); const cnt=Math.max(d.count||0,ds.length,1); const v=reorderVal(d); const opts=[d.size,d.sweet?d.sweet+" sweet":"",d.ice,d.milk?"🥛 "+d.milk:""].filter(Boolean); const last=ds.length?fmtDate(ds[ds.length-1]):""; const line2=reorderChip(d)+esc(opts.join(" · "))+((opts.length&&last)?" · ":"")+esc(last); const also=ds.length>1?'<div class="dalso">Also '+ds.slice(0,-1).map(fmtDate).join(" · ")+'</div>':''; return '<div class="drink'+(v?" v-"+v:"")+'"><div class="dmain"><div class="dtop">'+esc(d.n)+(cnt>1?' <span class="cnt">×'+cnt+'</span>':'')+(drinkMatches(d)?' <span class="dscore">'+drinkScore(d)+'</span>':'')+'</div>'+(line2.trim()?'<div class="dsub">'+line2+'</div>':'')+also+'</div><span class="pr">'+esc(fmtPrice(d.p))+'</span></div>'; }).join(""):'<div class="row" style="color:var(--faint);font-style:italic">'+(isAdmin?"Tap ＋ Log a drink here below.":"No drinks logged yet.")+"</div>"; const _dir=$("d-dir"); if(_dir)_dir.style.display=(c.custom&&c.lat==null)?"none":""; $("d-review").textContent=c.review||(isAdmin?"Tap ✎ Edit to add your thoughts…":"No notes yet."); show("detail"); if(c.lat!=null&&gmap)setTimeout(()=>{ mapResize(); gmap.setCenter({lat:c.lat,lng:c.lng}); gmap.setZoom(15); },80); }
function toggleFav(){ const c=cafes.find(x=>x.id===curId); if(!c)return; c.fav=!c.fav; save(); $("d-fav").textContent=c.fav?"❤️":"🤍"; renderMarkers(); toast(c.fav?"Added to favorites":"Removed from favorites"); }
function toggleWish(){ const c=cafes.find(x=>x.id===curId); if(!c)return; c.wish=!c.wish; save(); $("d-wish").style.opacity=c.wish?"1":".45"; renderMarkers(); toast(c.wish?"Added to wishlist 🔖":"Removed from wishlist"); }
function deleteCurrent(){ if(!confirm("Delete this cafe?"))return; cafes=cafes.filter(x=>x.id!==curId); save(); renderMarkers(); toast("Deleted"); goBack(); }
function cafeShareUrl(id){ const base=location.origin+location.pathname; return base+'?cafe='+encodeURIComponent(id); }
function shareCafe(){ const c=cafes.find(x=>x.id===curId); if(!c)return; const url=cafeShareUrl(c.id); const title=c.name+(c.area?' ('+c.area+')':''); const text='Check out '+c.name+(c.area?' in '+c.area:'')+' '+'★'.repeat(c.rating||0); if(navigator.share){ navigator.share({title:title,text:text,url:url}).catch(e=>{ if(e&&e.name!=='AbortError'){ navigator.clipboard&&navigator.clipboard.writeText(url); toast('Link copied!'); } }); } else { navigator.clipboard&&navigator.clipboard.writeText(url); toast('Link copied! Share it to open this cafe on the map.'); } }
function navigateTo(){ const c=cafes.find(x=>x.id===curId); if(!c)return; const dest=(c.lat!=null&&c.lng!=null)?(c.lat+","+c.lng):encodeURIComponent(c.name+(c.area?" "+c.area:"")); const url="https://www.google.com/maps/dir/?api=1&destination="+dest; if(window.innerWidth>=900){ window.open(url,"_blank"); } else { window.location.href=url; } }
function editCurrent(){ openForm(curId); }
