"use strict";
/* form.js — Add/edit visit form and quick log sheet.
   Loaded by index.html; script order matters (config first, boot last). */
/* ---------- form ---------- */
function checkExisting(){ if(editId)return; const name=$("f-name").value.trim(); if(!name)return; const ex=findSameCafe(name,$("f-area").value.trim(),picked?picked.lat:null,picked?picked.lng:null); if(ex){ openForm(ex.id); toast("Found "+ex.name+" — loaded your notes to edit"); } }
function fmtEdited(iso){ if(!iso)return ""; const d=new Date(iso); if(isNaN(d))return ""; return d.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})+" · "+d.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"}); }
function openForm(id){ editId=(typeof id==="string")?id:null; const c=editId?cafes.find(x=>x.id===editId):null; $("form-title").textContent=c?"Edit visit":"Add a visit"; $("f-name").value=c?c.name:""; $("f-area").value=c?(c.area||""):""; if($("f-brand"))$("f-brand").value=c?(c.brand||""):""; $("f-review").value=c?(c.review||""):""; $("f-fav").checked=c?!!c.fav:false; if($("f-wish"))$("f-wish").checked=c?!!c.wish:false; if($("f-custom"))$("f-custom").checked=c?!!c.custom:false; formPhoto=c?(c.photo||null):null; formRating=c?(c.rating||0):0; formTags=c?(c.tags||[]).slice():[]; picked=c&&c.lat!=null?{lat:c.lat,lng:c.lng}:null; if($("f-photo-url"))$("f-photo-url").value=(formPhoto&&!String(formPhoto).startsWith("data:"))?formPhoto:""; renderPhoto(); renderRate(); renderTags(); renderDrinkRows(c?c.drinks:null); _formSnap=formSnapshot(); show("form"); setTimeout(initFormMap,90); }
/* Unsaved-changes guard: snapshot the form on open, compare on any exit path (close button, back button, tab/nav via show(), page unload). Saving clears the snapshot so it never prompts. Pin coords are normalized to 5 decimals because setPicked rounds them. */
let _formSnap=null;
function formSnapshot(){ const rows=[...document.querySelectorAll("#f-drinks .dr")].map(r=>{ const g=cl=>{ const el=r.querySelector(cl); return el?el.value:""; }; const gs=cl=>{ const el=r.querySelector(cl); return el?(el.value+":"+((el.dataset&&el.dataset.set)||"")):""; }; return [g(".dn"),g(".dp"),g(".dd"),gs(".dsz"),gs(".dsw"),gs(".dic"),g(".dmk"),g(".dre")].join("|"); }).filter(s=>s.split("|")[0].trim()); return JSON.stringify([$("f-name").value,$("f-area").value,$("f-brand")?$("f-brand").value:"",$("f-review").value,$("f-fav").checked,$("f-wish")?$("f-wish").checked:false,$("f-custom")?$("f-custom").checked:false,formPhoto,formRating,formTags,picked?[+(+picked.lat).toFixed(5),+(+picked.lng).toFixed(5)]:null,rows]); }
function formDirty(){ return _formSnap!==null && app.dataset.view==="form" && formSnapshot()!==_formSnap; }
function closeForm(){ if(formDirty()&&!confirm("Discard unsaved changes to this visit?"))return; _formSnap=null; if(editId)show("detail"); else if(wishOnly)show("wish"); else if(favOnly)show("list",true); else show(lastMain); }
function initFormMap(){ if(!gReady)return; const start=picked?{lat:picked.lat,lng:picked.lng}:{lat:DEFAULT_CENTER[0],lng:DEFAULT_CENTER[1]}; if(!fgmap){ fgmap=new google.maps.Map($("form-map"),{center:start,zoom:13,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,clickableIcons:false,gestureHandling:"greedy"}); fgmap.addListener("click",e=>setPicked(e.latLng.lat(),e.latLng.lng())); try{ const ac=new google.maps.places.Autocomplete($("f-name"),{fields:["name","geometry","address_components"]}); ac.addListener("place_changed",()=>{ const p=ac.getPlace(); if(p.geometry&&p.geometry.location){ const loc=p.geometry.location; setPicked(loc.lat(),loc.lng()); fgmap.setCenter(loc); fgmap.setZoom(16); } if(p.name)$("f-name").value=p.name; if(p.address_components&&!$("f-area").value){ const nb=p.address_components.find(x=>x.types.includes("neighborhood")||x.types.includes("sublocality")||x.types.includes("locality")); if(nb)$("f-area").value=nb.long_name; } checkExisting(); }); }catch(e){} try{ const ac2=new google.maps.places.Autocomplete($("f-area"),{fields:["geometry","name"],types:["geocode"]}); ac2.addListener("place_changed",()=>{ const p=ac2.getPlace(); if(p.geometry&&p.geometry.location){ const loc=p.geometry.location; fgmap.setCenter(loc); fgmap.setZoom(15); if(!picked)setPicked(loc.lat(),loc.lng()); } if(p.name)$("f-area").value=p.name; }); }catch(e){} } google.maps.event.trigger(fgmap,"resize"); fgmap.setCenter(start); if(picked)setPicked(picked.lat,picked.lng); else if(fgmarker){ fgmarker.setMap(null); fgmarker=null; $("f-coords").textContent=""; } }
function setPicked(lat,lng){ picked={lat:+lat.toFixed(5),lng:+lng.toFixed(5)}; if(fgmarker)fgmarker.setMap(null); fgmarker=new google.maps.Marker({position:{lat:picked.lat,lng:picked.lng},map:fgmap}); $("f-coords").textContent=picked.lat+", "+picked.lng; }
function formLocate(){ if(!navigator.geolocation){ toast("Location not available"); return; } navigator.geolocation.getCurrentPosition(p=>{ if(fgmap){ fgmap.setCenter({lat:p.coords.latitude,lng:p.coords.longitude}); fgmap.setZoom(15); } setPicked(p.coords.latitude,p.coords.longitude); },()=>toast("Couldn't get location")); }
function renderPhoto(){ const d=$("f-photodrop"); const icon=d.querySelector("div"); if(formPhoto){ d.style.backgroundImage='url("'+safeUrl(formPhoto)+'")'; if(icon)icon.style.display="none"; $("f-photolabel").textContent=""; } else { d.style.backgroundImage=""; if(icon)icon.style.display=""; $("f-photolabel").textContent="Paste an image link below to preview"; } }
function onPhotoUrl(){ const v=$("f-photo-url").value.trim(); formPhoto=v||null; renderPhoto(); const s=$("f-photo-status"); if(!s)return; if(!v){ s.textContent=""; return; } s.textContent="Checking link…"; s.style.color="var(--soft)"; const t=new Image(); t.onload=()=>{ s.textContent="✓ Image loaded"; s.style.color="#3aa76d"; }; t.onerror=()=>{ s.textContent='⚠ Couldn\'t load this link — use the photo\'s "Copy image address" link, not the Share link.'; s.style.color="var(--acc2)"; }; t.src=v; }
function renderRate(){ $("f-rate").innerHTML=[1,2,3,4,5].map(n=>'<span class="'+(n<=formRating?"on":"")+'" onclick="formRating='+n+';renderRate()">★</span>').join(""); }
function renderTags(){ $("f-tags").innerHTML=ALL_TAGS.map(t=>'<span class="chip '+(formTags.includes(t)?"on":"")+'" onclick="toggleTag(\''+t+'\')">'+t+'</span>').join(""); }
function toggleTag(t){ formTags.includes(t)?formTags=formTags.filter(x=>x!==t):formTags.push(t); renderTags(); }
function renderDrinkRows(drinks){ $("f-drinks").innerHTML=""; const rows=[]; (drinks&&drinks.length?drinks:[{n:"",p:""}]).forEach(d=>{ const ds=(d.dates||[]).filter(Boolean); const cnt=Math.max(d.count||0,ds.length,1); for(let i=0;i<cnt;i++)rows.push({n:d.n,p:d.p,date:ds[i]||"",sweet:d.sweet,ice:d.ice,size:d.size,milk:d.milk,reorder:d.reorder}); }); rows.sort((a,b)=>(b.date||"").localeCompare(a.date||"")); const KEEP=3; const hideFrom=(rows.length>KEEP+1)?KEEP:rows.length; rows.forEach((r,i)=>addDrinkRow(r.n,r.p,r.date,r.sweet,r.ice,r.size,r.reorder,i>=hideFrom,r.milk)); const hidden=rows.length-hideFrom; if(hidden>0){ const b=document.createElement("button"); b.type="button"; b.className="hintbtn dr-oldertoggle"; b.textContent="⌛ Show "+hidden+" older visit"+(hidden===1?"":"s")+" ▾"; b.onclick=function(){ document.querySelectorAll("#f-drinks .dr-old").forEach(e=>{ e.style.display=""; }); this.remove(); }; $("f-drinks").appendChild(b); } }
function drinkRowLabel(dr){ const g=cls=>{ const el=dr.querySelector(cls); return el?el.value:""; }; const parts=[(g(".dn")||"").trim()||"New drink"]; const p=(g(".dp")||"").trim(); if(p)parts.push(fmtPrice(p)); const d=g(".dd"); if(d)parts.push(fmtDate(d)); return parts.join(" · "); }
const MILKS=["Whole","2%","Skim","Oat","Almond","Soy","Coconut","Macadamia","Lactose-free","Half & half","None"];
function setMilk(btn){ const wrap=btn.closest(".mkwrap"); const hid=wrap.querySelector(".dmk"); const v=btn.dataset.milk; hid.value=(hid.value===v)?"":v; wrap.querySelectorAll(".mkbtn").forEach(b=>b.classList.toggle("on",!!hid.value&&b.dataset.milk===hid.value)); }
function toggleDrinkRow(btn){ const dr=btn.closest(".dr"); const c=dr.classList.toggle("collapsed"); btn.querySelector(".drchev").textContent=c?"▸":"▾"; if(c)btn.querySelector(".drtitle").textContent=drinkRowLabel(dr); }
function addDrinkRow(n,p,date,sweet,ice,size,reorder,old,milk){ const re=(reorder==="yes"||reorder===true)?"yes":((reorder==="no"||reorder===false)?"no":(reorder==="neutral"?"neutral":"")); const sv=parseInt(String(sweet||"").replace(/[^0-9]/g,""),10); const hasSweet=!isNaN(sv); const sval=hasSweet?sv:50; /* Ice/Temp runs coldest (left) to hottest (right). Stored values are the labels themselves, so reordering the scale doesn't touch saved data. */
const ICS=["Extra ice","Regular ice","Less ice","No ice","Warm","Hot"]; const iv=ICS.indexOf(ice||""); const hasIce=iv>=0; const ival=hasIce?iv:3; const zoz=parseInt(String(size||"").replace(/[^0-9]/g,""),10); const hasSize=!isNaN(zoz); const zval=hasSize?Math.max(8,Math.min(32,Math.round(zoz/2)*2)):16; const collapsed=!!(n&&String(n).trim()); const title=esc(((n||"").trim()||"New drink")+((p&&String(p).trim())?" · "+fmtPrice(p):"")+(date?" · "+fmtDate(date):"")); const div=document.createElement("div"); div.className="dr"+(collapsed?" collapsed":""); div.innerHTML='<button type="button" class="drhead" onclick="toggleDrinkRow(this)"><span class="drchev">'+(collapsed?"▸":"▾")+'</span><span class="drtitle">'+title+'</span><span class="dredit">✎</span></button><input class="dn" type="text" autocomplete="off" placeholder="Drink" value="'+esc(n||"")+'"><input class="dp" type="text" autocomplete="off" placeholder="Price" value="'+esc(p||"")+'"><input class="dd" type="date" value="'+esc(date||"")+'"><div class="szwrap"><span class="swlabel">Cup size</span><input class="dsz" type="range" min="8" max="32" step="2" value="'+zval+'" data-set="'+(hasSize?1:0)+'" oninput="this.dataset.set=\'1\';this.parentNode.querySelector(\'.szval\').textContent=this.value+\' oz\';"><span class="szval">'+(hasSize?zval+" oz":"—")+'</span></div><div class="swwrap"><span class="swlabel">Sweetness</span><input class="dsw" type="range" min="0" max="100" step="5" value="'+sval+'" data-set="'+(hasSweet?1:0)+'" oninput="this.dataset.set=\'1\';this.parentNode.querySelector(\'.swval\').textContent=this.value+\'%\';"><span class="swval">'+(hasSweet?sval+"%":"—")+'</span></div><div class="icwrap"><span class="swlabel">Ice / Temp</span><input class="dic" type="range" min="0" max="5" step="1" value="'+ival+'" data-set="'+(hasIce?1:0)+'" data-labels="Extra ice|Regular ice|Less ice|No ice|Warm|Hot" oninput="this.dataset.set=\'1\';this.parentNode.querySelector(\'.icval\').textContent=this.dataset.labels.split(\'|\')[this.value];"><span class="icval">'+(hasIce?ICS[iv]:"—")+'</span></div><div class="mkwrap"><span class="swlabel">Milk</span>'+MILKS.map(function(mk){ return '<button type="button" class="mkbtn'+(mk===milk?" on":"")+'" data-milk="'+esc(mk)+'" onclick="setMilk(this)">'+esc(mk)+'</button>'; }).join("")+'<input type="hidden" class="dmk" value="'+esc(milk||"")+'"></div><div class="rowrap"><span class="swlabel">Rate it</span><button type="button" class="rbtn yes'+(re==="yes"?" on":"")+'" onclick="setReorder(this,\'yes\')">👍</button><button type="button" class="rbtn neutral'+(re==="neutral"?" on":"")+'" onclick="setReorder(this,\'neutral\')">😐</button><button type="button" class="rbtn no'+(re==="no"?" on":"")+'" onclick="setReorder(this,\'no\')">👎</button><input type="hidden" class="dre" value="'+re+'"></div><button class="delrow" onclick="this.parentNode.remove()">✕</button>'; if(old){ div.classList.add("dr-old"); div.style.display="none"; } $("f-drinks").appendChild(div); }
function visitCount(d){ const ds=(d&&d.dates||[]).filter(Boolean); return Math.max((d&&d.count)||0, ds.length, 1); }
function findSameCafe(name,area,lat,lng){ const nm=(name||"").trim().toLowerCase(); if(!nm)return null; return cafes.find(c=>{ if((c.name||"").trim().toLowerCase()!==nm)return false; if(lat!=null&&c.lat!=null)return Math.abs(lat-c.lat)<0.004&&Math.abs(lng-c.lng)<0.004; const a1=(area||"").trim().toLowerCase(), a2=(c.area||"").trim().toLowerCase(); if(a1&&a2)return a1===a2; return true; })||null; }
function mergeVisitInto(c,data){ c.drinks=c.drinks||[]; (data.drinks||[]).forEach(nd=>{ const k=nd.n.toLowerCase(); const ex=c.drinks.find(d=>d.n.toLowerCase()===k); if(ex){ if(nd.p)ex.p=nd.p; if(nd.size)ex.size=nd.size; if(nd.sweet)ex.sweet=nd.sweet; if(nd.ice)ex.ice=nd.ice; if(nd.milk)ex.milk=nd.milk; if(nd.reorder)ex.reorder=nd.reorder; const dates=[...new Set([...(ex.dates||[]),...(nd.dates||[])])].filter(Boolean).sort(); const cnt=visitCount(ex)+visitCount(nd); if(dates.length)ex.dates=dates; if(cnt>1)ex.count=Math.max(cnt,dates.length); } else { c.drinks.push(nd); } }); c.tags=[...new Set([...(c.tags||[]),...(data.tags||[])])]; if(data.fav)c.fav=true; if(data.rating)c.rating=data.rating; if(data.photo&&!c.photo)c.photo=data.photo; if(!c.area&&data.area)c.area=data.area; if(c.lat==null&&data.lat!=null){ c.lat=data.lat; c.lng=data.lng; } if(data.review){ c.review=c.review?(c.review.indexOf(data.review)>=0?c.review:(c.review+"\n\n"+data.review)):data.review; } if(data.updated)c.updated=data.updated; }
function saveForm(){ try{ const name=$("f-name").value.trim(); if(!name){ toast("Please add a cafe name"); return; } const raw=[...document.querySelectorAll("#f-drinks .dr")].map(r=>{ const dn=r.querySelector(".dn"),dp=r.querySelector(".dp"),dsz=r.querySelector(".dsz"),dd=r.querySelector(".dd"),dsw=r.querySelector(".dsw"),dic=r.querySelector(".dic"),dre=r.querySelector(".dre"),dmk=r.querySelector(".dmk"); return {n:dn?dn.value.trim():"",p:dp?dp.value.trim():"",size:(dsz&&dsz.dataset.set==="1")?(dsz.value+" oz"):"",date:dd?dd.value:"",sweet:(dsw&&dsw.dataset.set==="1")?(dsw.value+"%"):"",ice:(dic&&dic.dataset.set==="1")?(dic.dataset.labels.split("|")[dic.value]):"",milk:dmk?dmk.value:"",reorder:dre?dre.value:""}; }).filter(d=>d.n); const dmap=new Map(); raw.forEach(d=>{ const k=d.n.toLowerCase(); if(!dmap.has(k))dmap.set(k,{n:d.n,p:d.p,dates:[],count:0}); const e=dmap.get(k); if(d.p&&!e.p)e.p=d.p; if(d.size)e.size=d.size; if(d.sweet)e.sweet=d.sweet; if(d.ice)e.ice=d.ice; if(d.milk)e.milk=d.milk; if(d.reorder)e.reorder=d.reorder; e.count++; if(d.date&&!e.dates.includes(d.date))e.dates.push(d.date); }); const drinks=[...dmap.values()].map(d=>{ d.dates.sort(); const o={n:d.n,p:d.p}; if(d.size)o.size=d.size; if(d.sweet)o.sweet=d.sweet; if(d.ice)o.ice=d.ice; if(d.milk)o.milk=d.milk; if(d.reorder)o.reorder=d.reorder; if(d.dates.length)o.dates=d.dates; const cnt=Math.max(d.count,d.dates.length); if(cnt>1)o.count=cnt; return o; }); const data={name,area:$("f-area").value.trim(),brand:$("f-brand")?$("f-brand").value.trim():"",lat:picked?picked.lat:null,lng:picked?picked.lng:null,photo:formPhoto,rating:formRating,fav:$("f-fav").checked,wish:$("f-wish")?$("f-wish").checked:false,custom:$("f-custom")?$("f-custom").checked:false,tags:formTags.slice(),review:$("f-review").value.trim(),drinks,updated:new Date().toISOString()}; let savedId=editId, msg="Saved ✓"; const c=editId?cafes.find(x=>x.id===editId):null; if(c){ const moved=(c.lat!==data.lat||c.lng!==data.lng); Object.assign(c,data); if(moved){ delete gphotoCache[c.id]; if(c.gphoto)delete c.gphoto; saveGphotoCache(); } if(c.custom){ if(c.emoji==="☕")c.emoji="🏠"; if(c.gphoto){ delete c.gphoto; delete gphotoCache[c.id]; saveGphotoCache(); } } else if(c.emoji==="🏠")c.emoji="☕"; } else { const ex=findSameCafe(data.name,data.area,data.lat,data.lng); if(ex){ mergeVisitInto(ex,data); savedId=ex.id; msg="Added another visit to "+ex.name+" ✓"; } else { data.id=uid(); data.emoji=data.custom?"🏠":"☕"; savedId=data.id; cafes.push(data); } } save(); _formSnap=null; try{ renderMarkers(); }catch(e){ console.warn("renderMarkers failed",e); } try{ renderList(); }catch(e){} toast(msg); savedId?openDetail(savedId):show(lastMain); }catch(err){ console.error("saveForm failed",err); toast("Couldn't save — "+(err&&err.message?err.message:"unexpected error")); } }
/* ---------- quick log ---------- */
let _qRating=0, _qPickedId=null;
function openQuick(){ _qPickedId=null; _qRating=0; var qn=$('q-name'),qd=$('q-drink'); if(qn)qn.value=''; if(qd)qd.value=''; $('q-sugg').className='quick-sugg'; renderQuickRate(); $('quick-sheet').classList.add('show'); setTimeout(function(){ if(qn)qn.focus(); },140); }
function closeQuick(){ $('quick-sheet').classList.remove('show'); }
function renderQuickRate(){ $('q-rate').innerHTML=[1,2,3,4,5].map(function(n){ return '<span class="'+(n<=_qRating?'on':'')+('"')+' onclick="_qRating='+n+';renderQuickRate()">★</span>'; }).join(''); }
function quickSuggest(){ var v=($('q-name').value||'').toLowerCase().trim(); var sugg=$('q-sugg'); if(!v||v.length<1){ sugg.className='quick-sugg'; return; } var matches=cafes.filter(function(c){ return !c.wish&&(c.name||'').toLowerCase().includes(v); }).slice(0,5); if(!matches.length){ sugg.className='quick-sugg'; return; } sugg.innerHTML=matches.map(function(c){ return '<div class="qsi" onclick="quickPick(\''+c.id+'\')">'+'<span>'+esc(c.name)+'</span>'+(c.area?'<span class="qsi-sub">'+esc(c.area)+'</span>':'')+'</div>'; }).join(''); sugg.className='quick-sugg open'; }
function quickPick(id){ var c=cafes.find(function(x){ return x.id===id; }); if(!c)return; _qPickedId=id; $('q-name').value=c.name; $('q-sugg').className='quick-sugg'; if(!_qRating&&c.rating){ _qRating=c.rating; renderQuickRate(); } setTimeout(function(){ $('q-drink').focus(); },60); }
function saveQuick(){ var name=($('q-name').value||'').trim(); if(!name){ toast('Add a cafe name'); $('q-name').focus(); return; } var drinkName=($('q-drink').value||'').trim(); var drinks=drinkName?[{n:drinkName,dates:[new Date().toISOString().slice(0,10)]}]:[]; var data={name:name,area:'',brand:'',lat:null,lng:null,photo:null,rating:_qRating||0,fav:false,wish:false,tags:[],review:'',drinks:drinks,updated:new Date().toISOString()}; var savedId=null; var ex=_qPickedId?cafes.find(function(x){ return x.id===_qPickedId; }):findSameCafe(name,'',null,null); if(ex){ mergeVisitInto(ex,data); savedId=ex.id; } else { data.id=uid(); data.emoji='☕'; savedId=data.id; cafes.push(data); } _qPickedId=null; save(); try{ renderMarkers(); }catch(e){} try{ renderList(); }catch(e){} closeQuick(); toast('Logged ✓'); openDetail(savedId); }
