"use strict";
/* map.js — Google Maps loading, markers, location index and geolocation.
   Loaded by index.html; script order matters (config first, boot last). */
/* ---------- google maps loader ---------- */
function startMaps(){ if(!GMAPS_KEY_ENC||/PASTE|HERE/.test(GMAPS_KEY_ENC)){ showMapError("Add your encoded Google Maps API key near the top of this file (the GMAPS_KEY_ENC line), then reload."); return; } const s=document.createElement("script"); s.src="https://maps.googleapis.com/maps/api/js?key="+encodeURIComponent(GMAPS_KEY)+"&libraries=places&loading=async&callback=onGoogleReady"; s.async=true; s.onerror=()=>showMapError("Couldn't load Google Maps. Check your connection and API key."); document.head.appendChild(s); }
function onGoogleReady(){ gReady=true; $("map-msg").classList.remove("show"); initMap(); if(app.dataset.view==="list")renderList(); }
function gm_authFailure(){ showMapError("Google rejected the API key. Check the key is correct, billing is enabled, and this site is allowed in the key's HTTP-referrer restrictions."); }
function showMapError(msg){ const el=$("map-msg"); el.innerHTML='<div class="big">🗺️</div><div>'+msg+'</div>'; el.classList.add("show"); if($("map-sub"))$("map-sub").textContent="Map unavailable"; }
function mapResize(){ if(gmap)google.maps.event.trigger(gmap,"resize"); if(fgmap)google.maps.event.trigger(fgmap,"resize"); }
function fitPad(){ const w=window.innerWidth||0; if(w>=1400)return {top:60,right:60,bottom:60,left:480}; if(w>=900)return {top:60,right:60,bottom:60,left:440}; return 60; }
function refitMap(){ if(!gmap)return; const pts=gmarkers.map(m=>m.getPosition()).filter(Boolean); if(userMarker)pts.push(userMarker.getPosition()); if(!pts.length)return; if(pts.length===1){ gmap.setCenter(pts[0]); } else { const b=new google.maps.LatLngBounds(); pts.forEach(p=>b.extend(p)); gmap.fitBounds(b,fitPad()); } }
/* ---------- main map ---------- */
function initMap(){ gmap=new google.maps.Map($("map"),{center:{lat:DEFAULT_CENTER[0],lng:DEFAULT_CENTER[1]},zoom:12,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,clickableIcons:false,gestureHandling:"greedy"}); renderMarkers(); autoLocate(); gmap.addListener("click",()=>{ pendingMarkerId=null; if(gInfo)gInfo.close(); }); }
function ratingColor(r){ r=r||0; return r>=5?"#2e9e5b":r>=4?"#7cb342":r>=3?"#f0a93b":r>=2?"#ef7c2b":r>=1?"#e0556b":"#9aa0a6"; }
let gclusterer=null;
const _clusterRenderer={ render:function(cluster){ const n=cluster.count; return new google.maps.Marker({ position:cluster.position, icon:{ path:google.maps.SymbolPath.CIRCLE, scale:14+Math.min(12,n), fillColor:"#d5803b", fillOpacity:.92, strokeColor:"#ffffff", strokeWeight:3 }, label:{ text:String(n), color:"#ffffff", fontSize:"12px", fontWeight:"700" }, zIndex:google.maps.Marker.MAX_ZINDEX+n }); } };
function renderMarkers(){ if(!gmap)return; if(gclusterer){ try{ gclusterer.clearMarkers(); gclusterer.setMap(null); }catch(e){ warn("map.js",e); } gclusterer=null; } gmarkers.forEach(m=>m.setMap(null)); gmarkers=[]; const b=new google.maps.LatLngBounds(); let n=0; const dups=dupNameKeys(); cafes.forEach(c=>{ if(c.lat==null)return; const opt={position:{lat:c.lat,lng:c.lng},title:(dups[(c.name||"").trim().toLowerCase()]&&c.area)?(c.name+" — "+c.area):c.name,icon:c.wish?{path:google.maps.SymbolPath.CIRCLE,scale:10,fillColor:"#5b9bd5",fillOpacity:0.25,strokeColor:"#5b9bd5",strokeWeight:3}:{path:google.maps.SymbolPath.CIRCLE,scale:c.fav?15:12,fillColor:ratingColor(c.rating),fillOpacity:1,strokeColor:c.fav?"#e0556b":"#ffffff",strokeWeight:c.fav?4:3},zIndex:c.wish?1:(c.fav?5:3)}; const m=new google.maps.Marker(opt); m.addListener("click",()=>onMarkerClick(c,m)); gmarkers.push(m); b.extend(opt.position); n++; }); if(window.markerClusterer&&markerClusterer.MarkerClusterer&&gmarkers.length){ gclusterer=new markerClusterer.MarkerClusterer({ map:gmap, markers:gmarkers, renderer:_clusterRenderer }); } else { gmarkers.forEach(m=>m.setMap(gmap)); } if($("map-sub"))$("map-sub").textContent=cafes.length+" cafe"+(cafes.length===1?"":"s")+" · tap a pin"; renderLocationSelect(); if(n===1){ gmap.setCenter(gmarkers[0].getPosition()); gmap.setZoom(14); } else if(n>1){ gmap.fitBounds(b,fitPad()); } }
const COUNTRY_INFO={"United States USA America":{flag:"🇺🇸",name:"United States"},"South Korea Korea":{flag:"🇰🇷",name:"South Korea"},"Japan":{flag:"🇯🇵",name:"Japan"},"Taiwan":{flag:"🇹🇼",name:"Taiwan"},"Hong Kong China":{flag:"🇭🇰",name:"Hong Kong"},"Singapore":{flag:"🇸🇬",name:"Singapore"},"Australia":{flag:"🇦🇺",name:"Australia"},"United Kingdom UK England":{flag:"🇬🇧",name:"United Kingdom"},"France":{flag:"🇫🇷",name:"France"}};
function cafeCountryName(c){ const t=countryTerms(c); return (COUNTRY_INFO[t]&&COUNTRY_INFO[t].name)||"Other"; }
function cafeCountryLabel(c){ const t=countryTerms(c); const info=COUNTRY_INFO[t]; return info?(info.flag+" "+info.name):"🌐 Other"; }
function cafeStateName(c){ const m=/,\s*([A-Za-z]{2})\b/.exec(c.area||""); if(m){ const ab=m[1].toUpperCase(); if(STATE_NAMES[ab])return STATE_NAMES[ab]; } if(c.lat!=null&&c.lng!=null){ const lat=c.lat,lng=c.lng; if(lng<-150&&lat>18&&lat<23)return "Hawaii"; if(lng>=-125&&lng<=-117&&lat>=32&&lat<=42.5)return "California"; if(lng>-117&&lng<=-114&&lat>=35&&lat<=37.5)return "Nevada"; } return ""; }
function buildLocationIndex(){ const groups={}; cafes.forEach(c=>{ if(c.lat==null)return; const name=cafeCountryName(c); const label=cafeCountryLabel(c); const st=cafeStateName(c); const city=(c.area||"").trim(); if(!groups[name])groups[name]={label:label,states:{},cities:{},isUS:name==="United States"}; if(st){ if(!groups[name].states[st])groups[name].states[st]={cities:{}}; if(groups[name].isUS&&city)groups[name].states[st].cities[city]=true; } else if(groups[name].isUS&&city){ groups[name].cities[city]=true; } }); return groups; }
function renderLocationSelect(){ const sel=$("locsel"); if(!sel)return; const prev=sel.value; const groups=buildLocationIndex(); const names=Object.keys(groups).sort((a,b)=>a==="Other"?1:(b==="Other"?-1:a.localeCompare(b))); let html='<option value="">📍 All locations</option>'; names.forEach(name=>{ const g=groups[name]; html+='<optgroup label="'+esc(g.label)+'">'; html+='<option value="country:'+encodeURIComponent(name)+'">All of '+esc(name)+'</option>'; const states=Object.keys(g.states).sort(); states.forEach(s=>{ html+='<option value="state:'+encodeURIComponent(name)+'|'+encodeURIComponent(s)+'">'+esc(s)+'</option>'; if(g.isUS){ const cities=Object.keys(g.states[s].cities).sort(); cities.forEach(ct=>{ html+='<option value="city:'+encodeURIComponent(name)+'|'+encodeURIComponent(s)+'|'+encodeURIComponent(ct)+'"> '+esc(ct)+'</option>'; }); } }); if(g.isUS){ const loose=Object.keys(g.cities).sort(); loose.forEach(ct=>{ html+='<option value="city:'+encodeURIComponent(name)+'||'+encodeURIComponent(ct)+'">'+esc(ct)+'</option>'; }); } html+='</optgroup>'; }); sel.innerHTML=html; if(prev&&[].slice.call(sel.options).some(o=>o.value===prev))sel.value=prev; }
function jumpToLocation(val){ if(!gmap){ if(app.dataset.view!=="map")show("map"); return; } mapJumped=!!val; let list; if(!val)list=cafes.filter(c=>c.lat!=null); else if(val.slice(0,8)==="country:"){ const name=decodeURIComponent(val.slice(8)); list=cafes.filter(c=>c.lat!=null&&cafeCountryName(c)===name); } else if(val.slice(0,6)==="state:"){ const parts=val.slice(6).split("|"); const name=decodeURIComponent(parts[0]); const st=decodeURIComponent(parts[1]||""); list=cafes.filter(c=>c.lat!=null&&cafeCountryName(c)===name&&cafeStateName(c)===st); } else if(val.slice(0,5)==="city:"){ const parts=val.slice(5).split("|"); const name=decodeURIComponent(parts[0]); const st=decodeURIComponent(parts[1]||""); const ct=decodeURIComponent(parts[2]||""); list=cafes.filter(c=>c.lat!=null&&cafeCountryName(c)===name&&(c.area||"").trim()===ct&&(st?cafeStateName(c)===st:true)); } else list=cafes.filter(c=>c.lat!=null); if(app.dataset.view!=="map")show("map"); if(!list||!list.length)return; const _sel=$("locsel"); if(_sel&&val)setTimeout(()=>{ try{ _sel.value=""; }catch(e){ warn("map.js",e); } },350); setTimeout(()=>{ if(list.length===1){ gmap.setCenter({lat:list[0].lat,lng:list[0].lng}); gmap.setZoom(15); } else { const b=new google.maps.LatLngBounds(); list.forEach(c=>b.extend({lat:c.lat,lng:c.lng})); gmap.fitBounds(b,fitPad()); } },0); }
let userLoc=null; let mapJumped=false;
let gInfo=null, pendingMarkerId=null;
function mapInfo(){ if(!gInfo)gInfo=new google.maps.InfoWindow(); return gInfo; }
function onMarkerClick(c,m){ if(gInfo)gInfo.close(); openDetail(c.id,"map"); }
function nearestCafe(pos){ let best=null,bd=Infinity; cafes.forEach(c=>{ if(c.lat==null)return; const d=distKm(pos.lat,pos.lng,c.lat,c.lng); if(d<bd){bd=d;best=c;} }); return best; }
function focusNearest(){ if(!gmap)return; showUserLocation(true); }
function showUserLocation(center){ if(!navigator.geolocation)return; navigator.geolocation.getCurrentPosition(p=>{ const pos={lat:p.coords.latitude,lng:p.coords.longitude}; userLoc=pos; if(app.dataset.view==="list")renderList(); if(!gmap)return; if(userMarker){ userMarker.setMap(null); userMarker=null; } if(center&&!mapJumped){ const near=nearestCafe(pos); if(near){ const b=new google.maps.LatLngBounds(); b.extend(pos); b.extend({lat:near.lat,lng:near.lng}); gmap.fitBounds(b,fitPad()); google.maps.event.addListenerOnce(gmap,"idle",()=>{ if(gmap.getZoom()>16)gmap.setZoom(16); }); } else { gmap.setCenter(pos); gmap.setZoom(13); } } },()=>{ if(center)toast("Couldn't get your location"); },{enableHighAccuracy:true,timeout:8000,maximumAge:0}); }
function locate(){ if(!navigator.geolocation){ toast("Location not available"); return; } showUserLocation(true); }
function autoLocate(){ if(!navigator.geolocation)return; if(navigator.permissions&&navigator.permissions.query){ navigator.permissions.query({name:"geolocation"}).then(r=>{ if(r.state!=="denied")showUserLocation(true); }).catch(()=>showUserLocation(true)); } else { showUserLocation(true); } }
