"use strict";
/* photos.js — Cafe photo fetching (Places API) with cache and fallbacks.
   Loaded by index.html; script order matters (config first, boot last). */
/* ---------- list ---------- */
/* ---------- google place photo fallback ---------- */
let gphotoInflight={};
function saveGphotoCache(){ try{ localStorage.setItem("cafemap.gphotos",JSON.stringify(gphotoCache)); }catch(e){} }
/* Legacy PhotoService.GetPhoto URLs are bound to the session that created them — once stale, Google serves a placeholder error image with HTTP 200, so onerror probes can't detect the breakage. Never trust them from persisted data. */
function isSessionPhotoUrl(u){ return /PhotoService\.GetPhoto/.test(u||""); }
function gphotoFor(c){ if(!c)return null; if(c.photo)return c.photo; if(c.gphoto&&!isSessionPhotoUrl(c.gphoto))return c.gphoto; const entry=gphotoCache[c.id]; if(!entry)return null; if(typeof entry==="object"){ if(Date.now()-entry.ts>6*24*60*60*1000){ delete gphotoCache[c.id]; saveGphotoCache(); return null; } return entry.url; } return entry; }
function applyCardPhoto(id,url){ const el=document.querySelector('.card[data-id="'+id+'"] .ph'); if(!el)return; const c=cafes.find(x=>x.id===id); if(url){ _imgFail[id]=0; el.style.backgroundImage='url("'+safeUrl(url)+'")'; el.classList.remove("nophoto","loading"); el.classList.add("loaded"); el.textContent=(c&&c.fav)?"❤️":""; verifyCardPhoto(id,url); } else { el.classList.remove("loading","loaded"); el.classList.add("nophoto"); el.style.backgroundImage=""; el.style.background=c?nophotoBg(c.name):"#caa472"; el.innerHTML=c?nophotoHTML(c):"?"; } }
function fetchPlacePhoto(c,cb){ if(!c||c.id==null||c.lat==null){ cb&&cb(null); return; } if(gphotoCache[c.id]!==undefined){ cb&&cb(gphotoFor(c)); return; } let settled=false; const finish=(u,cache)=>{ if(settled)return; settled=true; clearTimeout(guard); if(u){ gphotoCache[c.id]={url:u,ts:Date.now()}; if(!isSessionPhotoUrl(u))saveGphotoCache(); } else if(cache&&gphotoCache[c.id]===undefined){ gphotoCache[c.id]=null; saveGphotoCache(); } cb&&cb(u); }; const guard=setTimeout(()=>finish(null,true),9000); if(!gReady||!window.google||!google.maps||!google.maps.places){ finish(null,false); return; } const q=(c.name+" "+(c.area||"")).trim(); const legacy=()=>{ try{ if(!google.maps.places.PlacesService){ finish(null,true); return; } const svc=new google.maps.places.PlacesService(gmap||document.createElement("div")); svc.findPlaceFromQuery({ query:q, fields:["photos"], locationBias:{lat:c.lat,lng:c.lng} },(res,status)=>{ let url=null; try{ if(status===google.maps.places.PlacesServiceStatus.OK && res && res[0] && res[0].photos && res[0].photos.length){ url=res[0].photos[0].getUrl({maxWidth:800,maxHeight:600}); } }catch(e){} finish(url,true); }); }catch(e){ finish(null,true); } }; const P=google.maps.places.Place; if(P&&P.searchByText){ P.searchByText({ textQuery:q, fields:["photos"], locationBias:{lat:c.lat,lng:c.lng}, maxResultCount:1 }).then(r=>{ let url=null; try{ const p=r&&r.places&&r.places[0]; if(p&&p.photos&&p.photos.length)url=p.photos[0].getURI({maxWidth:800,maxHeight:600}); }catch(e){} if(url)finish(url,true); else legacy(); }).catch(legacy); } else legacy(); }
/* Thumbnails load lazily: a cafe's photo is only fetched when its detail page opens (openDetail), then the list card picks it up from the cache. Keeps Places API usage to one lookup per viewed cafe instead of one per listed cafe. */
/* Admin bulk action: fetch a photo for every cafe once and persist the stable URLs to Firebase (c.gphoto), so all viewers get instant thumbnails with zero API requests. Session-bound URLs are never persisted; the verify probe self-heals any URL that later dies. */
let _fapRunning=false;
async function fetchAllPhotos(){ if(_fapRunning)return; if(!isAdmin){ toast("Sign in to edit first"); return; } if(!gReady){ toast("Maps not ready yet — try again in a moment"); return; } const targets=cafes.filter(c=>c.lat!=null&&!c.photo&&!(c.gphoto&&!isSessionPhotoUrl(c.gphoto))); if(!targets.length){ toast("All cafes already have a photo ✓"); return; } _fapRunning=true; const total=targets.length; toast("Fetching photos for "+total+" cafes…"); let done=0,got=0; const queue=targets.slice(); const worker=async()=>{ while(queue.length){ const c=queue.shift(); delete gphotoCache[c.id]; await new Promise(res=>fetchPlacePhoto(c,(url)=>{ if(url&&!isSessionPhotoUrl(url)){ c.gphoto=url; got++; } done++; if(done%10===0||done===total)toast(done+" / "+total+" fetched…"); res(); })); } }; try{ await Promise.all([worker(),worker(),worker()]); } finally{ _fapRunning=false; } saveGphotoCache(); save(); if(app.dataset.view==="list")renderList(); toast("Saved "+got+" of "+total+" photos ✓"); }
